version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"
    HUGO_VERSION: "0.31.1"
    HUGO_SHA256: "b063aa750ce9f0d11e62662a0afa60f16845faadc3df13902c92d17fcbe80c47"
    HUGO_ENV: "production"

phases:
  install:
    commands:
      - curl -Ls https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - echo "${HUGO_SHA256}  /tmp/hugo.tar.gz" | sha256sum -c -
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
  pre_build:
    commands:
      - rmdir themes/beautifulhugo     
      - git init
      - git submodule add https://github.com/halogenica/beautifulhugo.git themes/beautifulhugo
      - (cd themes/beautifulhugo/ && git reset --hard b2ea7d9)
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws configure set preview.cloudfront true
      - aws s3 sync --delete public s3://edutech.ninja --cache-control max-age=3600
      - aws cloudfront create-invalidation --distribution-id E2KXMW6T1PVN76 --paths /index.html / /page/*

